services:
  - type: web
    name: yahtzee
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true